using System;
using System.Collections.Generic;

namespace ApiIosep.Models.IOSEP
{
    public partial class Est_Iosep
    {
        public int Id { get; set; }
        public string? O_SOCIAL { get; set; }
        public string? A_NUMERO { get; set; }
        public string? FAMILIAR { get; set; }
        public string? NOMBRE { get; set; }
        public string? SEXO { get; set; }
        public string? D_TIPO { get; set; }
        public string? D_NRO { get; set; }
        public string? E_CIVIL { get; set; }
        public string? NACIONALID { get; set; }
        public DateTime? N_FECHA { get; set; }
        public string? DOMICILIO { get; set; }
        public decimal? PUERTA { get; set; }
        public decimal? PISO { get; set; }
        public string? DTO { get; set; }
        public string? TELEFONO { get; set; }
        public string? DELEGACION { get; set; }
        public string? TIPO_DOM { get; set; }
        public string? PROVINCIA { get; set; }
        public string? ZONA { get; set; }
        public string? LOCALIDAD { get; set; }
        public string? EMPRESA { get; set; }
        public DateTime? I_FECHA { get; set; }
        public DateTime? V_FECHA { get; set; }
        public DateTime? C_FECHA { get; set; }
        public DateTime? VEN_FECHA { get; set; }
        public DateTime? F_ULT_CENS { get; set; }
        public DateTime? E_FECHA { get; set; }
        public string? CATEGORIA { get; set; }
        public decimal? ESTADO { get; set; }
        public bool? TRANSITO { get; set; }
        public bool? INCAPACIDA { get; set; }
        public string? Plan { get; set; }
        public string? CUIL { get; set; }
        public string? CTA_APO { get; set; }
        public string? SIT_LABORA { get; set; }
        public string? JUB_BENEF { get; set; }
        public decimal? ESTAFICHA { get; set; }
        public string? LETARC { get; set; }
        public decimal? CODARC { get; set; }
        public string? OBS { get; set; }
        public string? OBS2 { get; set; }
        public DateTime? FECHA { get; set; }
        public string? HORA { get; set; }
        public string? OPERADOR { get; set; }
        public decimal? TIPOAFIL { get; set; }
        public decimal? CANGRU { get; set; }
        public DateTime? FECVTOCAR { get; set; }
        public string? TIPO_DISC { get; set; }
        public DateTime? DIS_FDES { get; set; }
        public DateTime? DIS_FHAS { get; set; }
        public bool? MATERNO { get; set; }
        public DateTime? MAT_FDES { get; set; }
        public DateTime? MAT_FHAS { get; set; }
        public bool? ESTUDIAN { get; set; }
        public DateTime? EST_FDES { get; set; }
        public DateTime? EST_FHAS { get; set; }
        public decimal? ANO_LECT { get; set; }
        public string? CRED_ESPE { get; set; }
        public DateTime? F_CRED_E { get; set; }
        public DateTime? F_VENC_E { get; set; }
        public string? CRED_NORM { get; set; }
        public DateTime? F_CRED_N { get; set; }
        public DateTime? F_VENC_N { get; set; }
        public string? AF_TRANS { get; set; }
        public DateTime? F_TRAN_E { get; set; }
        public DateTime? F_TRAN_F { get; set; }
        public bool? DOCAFI { get; set; }
        public string? MOTIVO1 { get; set; }
        public decimal? APORTES { get; set; }
        public bool? CTROCOMP { get; set; }
        public bool? ANSES { get; set; }
        public bool? CONVENIO { get; set; }
        public string? PLAN_ESP { get; set; }
        public decimal? CANADI { get; set; }
        public string? TIPO_EMI { get; set; }
        public string? PROMOTOR { get; set; }
        public string? COBRADOR { get; set; }
        public DateTime? PLN_FECHA { get; set; }
        public string? TARJETA { get; set; }
        public string? NRO_TARJ { get; set; }
        public string? MED_CAB { get; set; }
        public bool? PARTO { get; set; }
        public DateTime? F_PARTO_D { get; set; }
        public DateTime? F_PARTO_H { get; set; }
        public decimal? T_IVA { get; set; }
        public string? CUIT { get; set; }
        public DateTime? F_ACTIVA { get; set; }
        public string? EMP_APORTE { get; set; }
        public decimal? IMP_APORTE { get; set; }
        public decimal? MES_APORTE { get; set; }
        public decimal? ANO_APORTE { get; set; }
        public decimal? PRO_APORTE { get; set; }
        public decimal? EDAD { get; set; }
        public bool? ART { get; set; }
    }
}
